from tkinter import *
import random
root = Tk()
root.title('Getting Bored: Have some fun!')
root.geometry('400x200')
root.maxsize(width = 400, height = 200)
num = random.randint(0,100)
count = 0
def get():
    global count
    guess= int(entry.get())
    count = count+1
    if guess ==num:
        result_label.config(text = f'Congratulations! You got it right in {count} times')
        entry.config(state = 'disabled')
        button.config(state = 'disabled')
    elif guess>num:
        result_label.config(text= 'Guess is too high')
    else:
        result_label.config(text = 'Guess is too low')
    entry.delete(0,END)




Label(root, text = 'Fun Time :) \nGuess the random number generated by Mr. Computer').pack()
entry = Entry(root)
entry.pack()
result_label = Label(root, text = '')
result_label.pack()
button = Button(root, text='SUBMIT', command = get)
button.pack()

















root.mainloop()